import type { Metadata } from "next";
import "./globals.css";
import ReactQueryWrapper from "@/components/ReactQuery";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased p-6 max-w-8xl mx-auto`}
      >
        <Navbar />
        <ReactQueryWrapper>{children}</ReactQueryWrapper>
      </body>
    </html>
  );
}
